configuration-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi

products-core-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 4
      memory: 6144Mi
    requests:
      cpu: 2
      memory: 4096Mi
  environment:
    SPRING_PROFILES_ACTIVE: uat
    SPRING_CLOUD_CONFIG_URI: http://ecomm-uat-configuration-service:8080
    JAVA_TOOL_OPTIONS: -XX:MaxDirectMemorySize=100M
  branches-etl-job:
    enabled: true
    schedule: "0 10 * * 6" # At 04:00 AM (CST) on Saturdays
    host: ecomm-uat-products-core-service
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  livenessProbe:
    path: "/actuator/health/liveness"
    initialDelaySeconds: 80
    periodSeconds: 10

  readinessProbe:
    path: "/actuator/health/readiness"
    initialDelaySeconds: 80
    periodSeconds: 10

account-management-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: uat
    SPRING_CLOUD_CONFIG_URI: http://ecomm-uat-configuration-service:8080
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

eclipse-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::187728244752:role/eclipse-service-role"
    name: ""
  eclipseIp: 192.168.154.106
  eclipseHostName: ewitest.morsco.com
  eclipseApiIp: 192.168.153.11
  eclipseApiHostName: apitest.morsco.com
  kourierIp: 10.255.184.77
  kourierHostName: rnirvwvkgated01.ad.morsco.com
  environment:
    SPRING_PROFILES_ACTIVE: uat
    SPRING_CLOUD_CONFIG_URI: http://ecomm-uat-configuration-service:8080
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

mincron-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: uat
    SPRING_CLOUD_CONFIG_URI: http://ecomm-uat-configuration-service:8080

mincron-adapter-poc:
  environment:
    SPRING_PROFILES_ACTIVE: uat
    SPRING_CLOUD_CONFIG_URI: http://ecomm-uat-configuration-service:8080

notifications-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: uat
    SPRING_CLOUD_CONFIG_URI: http://ecomm-uat-configuration-service:8080

max-portal:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:307497767174:certificate/0f82596d-8ab4-4746-a4d4-b1aae07dc34c
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
    hosts:
      - paths:
          - path: /*
            pathType: ImplementationSpecific
  environment:
    REACT_APP_API_URL: "https://api.uat.ecomm.reecedev.us/"
    REACT_APP_OKTA_URL: "https://dev-432546.okta.com"
    REACT_APP_OKTA_CLIENT_ID: "0oa13b0b5bMKXZfJU4x7"
    REACT_APP_ENABLE_TRANSLATION_TEST: "false"
    REACT_APP_SEGMENT_API_KEY: "Pl02bgvESMF4HvCiB8If8HgqdfJCL3GE"
    REACT_APP_GOOGLE_API_KEY: "AIzaSyDEVmbEdAOo2i3dkRrGFnrA92ta7qJ08DM"
    REACT_APP_ENVIRONMENT: "uat"
    REACT_APP_CONTENTFUL_API_URL: "https://graphql.contentful.com/content/v1/spaces/32w9pi4zc4mq"
    REACT_APP_CONTENTFUL_API_KEY: "hSRbF7whhrDZplJ5xYzcc3T8HT_n10vCw90IoL7_IbE"
    REACT_APP_CONTENTFUL_PREVIEW_API_KEY: "fnKfnu_ieAyirTfV39Up55pfWtdFG5ZIt1vqR9IZiWg"
    REACT_APP_CONTENTFUL_PREVIEW_ENABLE: "false"
    REACT_APP_CONTENTFUL_ABOUTUS_ID: "13j7MQQu4r6gSXv6KLiTYX"

reece-api:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:307497767174:certificate/0f82596d-8ab4-4746-a4d4-b1aae07dc34c
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=90
    hosts:
      - paths:
          - "/*"
  environment:
    SPRING_PROFILES_ACTIVE: uat
    API_SECRET: ep8T8kZK3x
    API_URL_ACCOUNT_MANAGEMENT: "http://ecomm-uat-account-management-service:8080"
    API_URL_CONFIG: "http://ecomm-uat-configuration-service:8080"
    API_URL_BRANCH_SERVICE: "http://ecomm-uat-branches-service:8080"
    API_URL_PRODUCT_SERVICE: "http://ecomm-uat-products-core-service:8080"
    API_URL_ECLIPSE_SERVICE: "http://ecomm-uat-eclipse-service:8080"
    API_URL_MINCRON_SERVICE: "http://ecomm-uat-mincron-service:8080"
    API_URL_NOTIFICATION_SERVICE: "http://ecomm-uat-notifications-service:8080"
    OKTA_DOMAIN: https://dev-432546.okta.com
    OKTA_CLIENT_ID: 0oa13b0b5bMKXZfJU4x7
    WEBSMART_URL: http://10.255.226.72:8080/WebSmart-apiTest/customerJobList

order-status-job:
  schedule: "0 * * * *" # Every hour
  environment:
    API_URL_PRODUCT_SERVICE: http://ecomm-uat-products-core-service:8080
