configuration-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi

products-core-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 4
      memory: 6144Mi
    requests:
      cpu: 2
      memory: 4096Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080
    JAVA_TOOL_OPTIONS: -XX:MaxDirectMemorySize=100M
  full-index-job:
    enabled: false
    schedule: '0 10 * * *' # At 04:00 AM (CST)
    host: ecomm-dr-prod-products-core-service
  incremental-index-job:
    enabled: false
    schedule: '0 0-9,11-23 * * *' # Every hour, at 12:00 AM through 03:59 AM (CST) and 05:00 AM (CST) through 11:59 PM
    host: ecomm-dr-prod-products-core-service
  branches-etl-job:
    enabled: false
    schedule: '0 10 * * 6' # At 04:00 AM (CST) on Saturdays
    host: ecomm-dr-prod-products-core-service
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

account-management-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 4
      memory: 6144Mi
    requests:
      cpu: 2
      memory: 4096Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

eclipse-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::187728244752:role/eclipse-service-role"
    name: ""
  eclipseIp: 192.168.154.206
  eclipseHostName: ewi.morsco.com
  eclipseApiIp: 192.168.153.10
  eclipseApiHostName: api.morsco.com
  kourierIp: 10.255.184.80
  kourierHostName: rnirvwvkgatep01.ad.morsco.com
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

mincron-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080

mincron-adapter-poc:
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080

notifications-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080

branches-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080

inventory-core-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 4
      memory: 6144Mi
    requests:
      cpu: 2
      memory: 4096Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080

special-pricing-service:
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080
  networkDriveIp: 10.255.224.130
  networkDriveHostName: mscfileprint001.ad.morsco.com
  customers-sync-job:
    enabled: false
    schedule: '0 3 * * *' # At 03:00 AM (CST)
    host: ecomm-dr-prod-special-pricing-service
  products-sync-job:
    enabled: false
    schedule: '0 4 * * *' # At 04:00 AM (CST)
    host: ecomm-dr-prod-special-pricing-service
  special-prices-sync-job:
    enabled: false
    schedule: '0 5 * * *' # At 05:00 AM (CST)
    host: ecomm-dr-prod-special-pricing-service

max-portal:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:187728244752:certificate/330c83ef-8836-404b-8b4e-08fee630c49d
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
    hosts:
      - paths:
          - path: /*
            pathType: ImplementationSpecific
  environment:
    REACT_APP_API_URL: "https://api.dr-prod.ecomm.reecedev.us/"
    REACT_APP_OKTA_URL: "https://reeceusadigital.okta.com"
    REACT_APP_OKTA_CLIENT_ID: "0oaruo46qsI4M3LaN5d6"
    REACT_APP_ENABLE_TRANSLATION_TEST: false
    REACT_APP_SEGMENT_API_KEY: "2HfRhtscvgjBB1nJrOqrW4vp7ZJaLM3N"
    REACT_APP_GOOGLE_API_KEY: "AIzaSyDEVmbEdAOo2i3dkRrGFnrA92ta7qJ08DM"
    PERCY_TOKEN: "a64bc29b0c9e10cc99885e87fd8a896f26d7d5d07f5cbe15612574342c6f0095"
    REACT_APP_ENVIRONMENT: "production-backup"
    REACT_APP_MAX_API_SECRET: "1upRhSWC1B"

wms-admin-portal:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:187728244752:certificate/330c83ef-8836-404b-8b4e-08fee630c49d
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
    hosts:
      - paths:
          - '/*'
  environment:
    REACT_APP_API_URL: 'https://api.dr-prod.internal.reecedev.us/'
    REACT_APP_OKTA_URL: 'https://morsco.okta.com'
    REACT_APP_OKTA_CLIENT_ID: '0oaho7jqcw56GpcKj357'
    REACT_APP_OKTA_SCOPES: 'openid profile email groups'
    REACT_APP_OKTA_CALLBACK: ''

reece-api:
  replicaCount: 2
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:187728244752:certificate/330c83ef-8836-404b-8b4e-08fee630c49d
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=90
    hosts:
      - paths:
          - '/*'
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    API_URL_ACCOUNT_MANAGEMENT: "http://ecomm-dr-prod-account-management-service:8080"
    API_URL_CONFIG: "http://ecomm-dr-prod-configuration-service:8080"
    API_URL_BRANCH_SERVICE: "http://ecomm-dr-prod-branches-service:8080"
    API_URL_PRODUCT_SERVICE: "http://ecomm-dr-prod-products-core-service:8080"
    API_URL_ECLIPSE_SERVICE: "http://ecomm-dr-prod-eclipse-service:8080"
    API_URL_MINCRON_SERVICE: "http://ecomm-dr-prod-mincron-service:8080"
    API_URL_NOTIFICATION_SERVICE: "http://ecomm-dr-prod-notifications-service:8080"
    OKTA_DOMAIN: https://reeceusadigital.okta.com
    OKTA_CLIENT_ID: 0oaruo46qsI4M3LaN5d6

internal-api:
  replicaCount: 2
  resources:
    limits:
      cpu: 4
      memory: 6144Mi
    requests:
      cpu: 2
      memory: 4096Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:187728244752:certificate/330c83ef-8836-404b-8b4e-08fee630c49d
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
      alb.ingress.kubernetes.io/scheme: internet-facing
    hosts:
      - paths:
          - '/*'
      
  environment:
    SPRING_PROFILES_ACTIVE: dr-prod
    API_URL_CONFIG: http://ecomm-dr-prod-configuration-service:8080
    API_URL_ACCOUNT_SERVICE: http://ecomm-dr-prod-account-management-service:8080
    API_URL_PRODUCT_SERVICE: http://ecomm-dr-prod-products-core-service:8080
    API_URL_INVENTORY_SERVICE: http://ecomm-dr-prod-inventory-core-service:8080
    API_URL_ECLIPSE_SERVICE: http://ecomm-dr-prod-eclipse-service:8080
    API_URL_MINCRON_SERVICE: http://ecomm-dr-prod-mincron-service:8080
    API_URL_PRICING_SERVICE: http://ecomm-dr-prod-special-pricing-service:8080
    OKTA_DOMAIN: https://morsco.okta.com
    OKTA_CLIENT_ID: 0oa7aiszsbZOlkrFK357

pi-batch-load-mincron:
  schedule: '*/30 4-23 * * *' # Every thirty minutes at the start of 4am through 11pm
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080
    NUM_CONCURRENT_OPERATIONS: 18
    CONFIG_ENV: dr-prod
    ERP: MINCRON

pi-batch-load-eclipse:
  schedule: '30 * * * *' #Every hour at the 30th minute
  resources:
    limits:
      cpu: 2
      memory: 3072Mi
    requests:
      cpu: 1
      memory: 2048Mi
  environment:
    SPRING_CLOUD_CONFIG_URI: http://ecomm-dr-prod-configuration-service:8080
    NUM_CONCURRENT_OPERATIONS: 18
    CONFIG_ENV: dr-prod
    ERP: ECLIPSE

order-status-job:
  schedule: '0 * * * *' # Every hour
  environment:
    API_URL_PRODUCT_SERVICE: http://ecomm-dr-prod-products-core-service:8080

